DELETE http://localhost:3003/api/blogs/64e79ac8bb699c1ea9087290

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RBIiwiaWQiOiI2NGVjMmUwMTcwMDQ5ZGFjMzQ4Njk2NTciLCJpYXQiOjE2OTM0NjE0ODZ9.-mMpYvBxo_BOjQItL9K5r1xBedqbwd7zBq-VST2kdYk
